### ISSUE TITLE
raw count matrix

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [ListerLab/pfc_development#2]
Hello!
Congratulations on this beautiful paper and data set.
I would like to explore the expression of particular genes. 
I am working in R, and I used:
anndata<-read_h5ad("Processed_data_RNA-all_full-counts-and-downsampled-CPM.h5ad") to obtain the anndate object. However, I don't know how to find the raw count matrix inside the object. Could you please guide me how can I get the raw count matrix from the anndata?
Thank you very much.
Best regards,
sofia

**Comment by herrinca** [comment]
Hi Sofia,

Thank you for your kind words! 

I primarly code in python and it has been a while since I tried to read an h5ad into R, so I am afraid I might not be much of a help. But here is a [link](https://drive.google.com/drive/folders/1MmnyNfNeQaomQhUU7joOOEB5aCjxfu-u?usp=sharing) to RDS files. 

I hope this helps.

Best,
Chuck

**Comment by herrinca** [comment]
Going to close this issue, please let us know if we can be of anymore help.
