### ISSUE TITLE
lack .uns["pca"]

### ISSUE THREAD

**Issue by ocean-debug** [ListerLab/pfc_development#8]
Hi herrinca ,

I am very interested in **uns["pca"]** , but the data you provided lacks this part . Is it convenient  for you to provide this part ?

Thanks,
ocean

**Comment by herrinca** [comment]
Hi ocean,

Thanks for your interest in our data.

I think the pca you are looking for can be found in the [anndata object](https://storage.googleapis.com/neuro-dev/Processed_data/RNA-all_full-counts-and-downsampled-CPM.h5ad) within adata.obsm['X_pca']. 

I hope this helps and let me know if you are after someting else.

Cheers,
Chuck

**Comment by ocean-debug** [comment]
Hi Chuck ,

Thanks for your help.
But I want the process data for PCA. It is usually stored in  adata.uns[’pca‘] and adata.varm['PCs']. In particular ,  **adata.varm['PCs']** stored the calculation matrix of pca.

Thanks,
ocean

**Comment by herrinca** [comment]
Oh, okay. I understand what you are after now.

As you already know, that is not included in the currently posted data, and that is because PCA was run on a subsetted adata consisting of only high variable genes. To reproduce the PCA from the paper and obtain the data you are after, you can run the following code:

```adata = sc.read( "/scratchfs/cherring/downsampling/RNA-all_full-counts-and-downsampled-CPM.h5ad")
adata.X = adata.layers['ds_norm_cts'].copy()
sc.pp.highly_variable_genes( adata, n_top_genes=5_000, n_bins=20, flavor='seurat', inplace=True)
high_adata = adata[:,adata.var.highly_variable.values]
sc.pp.pca( high_adata, n_comps=366)
```

This will reproduce the data from the publication. However, please note that to exactly reproduce the results, you will need to use all the library versions in the main_requirements.txt file located within the pfc_development/snRNAseq/notebooks/ directory.

I hope this helps you obtain the data you need. Let me know if you have any further questions!"

**Comment by ocean-debug** [comment]
Thanks for your help.
I obtain obtain I need.
Beautiful paper and data.
